# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("QWidget {\n"
"    color: black;\n"
"    font-family: Verdana;\n"
"    font-size: 12pt;\n"
"}\n"
"\n"
"QPushButton {\n"
"    border: 1px solid gray;\n"
"    border-radius: 5px;\n"
"    padding: 1px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border: 2px solid  black;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    border: 4px solid black;\n"
"    border-radius: 10px;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.DocumentsLabel = QtWidgets.QLabel(self.centralwidget)
        self.DocumentsLabel.setObjectName("DocumentsLabel")
        self.verticalLayout.addWidget(self.DocumentsLabel)
        self.DocumentsList = QtWidgets.QListWidget(self.centralwidget)
        self.DocumentsList.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.DocumentsList.setObjectName("DocumentsList")
        self.verticalLayout.addWidget(self.DocumentsList)
        self.DetailsBox = QtWidgets.QGroupBox(self.centralwidget)
        self.DetailsBox.setMinimumSize(QtCore.QSize(0, 0))
        self.DetailsBox.setObjectName("DetailsBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.DetailsBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.FNameLabel = QtWidgets.QLabel(self.DetailsBox)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.FNameLabel.setFont(font)
        self.FNameLabel.setObjectName("FNameLabel")
        self.verticalLayout_2.addWidget(self.FNameLabel)
        self.PathLabel = QtWidgets.QLabel(self.DetailsBox)
        self.PathLabel.setObjectName("PathLabel")
        self.verticalLayout_2.addWidget(self.PathLabel)
        self.verticalLayout.addWidget(self.DetailsBox)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.DoBtn = QtWidgets.QPushButton(self.centralwidget)
        self.DoBtn.setMinimumSize(QtCore.QSize(0, 50))
        self.DoBtn.setBaseSize(QtCore.QSize(0, 50))
        self.DoBtn.setObjectName("DoBtn")
        self.horizontalLayout.addWidget(self.DoBtn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.OnTopCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.OnTopCheckBox.setObjectName("OnTopCheckBox")
        self.verticalLayout.addWidget(self.OnTopCheckBox)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Scientific Notation Tool for Word"))
        self.DocumentsLabel.setText(_translate("MainWindow", "Opened Documents:"))
        self.DetailsBox.setTitle(_translate("MainWindow", "Details:"))
        self.FNameLabel.setText(_translate("MainWindow", "..."))
        self.PathLabel.setText(_translate("MainWindow", "..."))
        self.DoBtn.setText(_translate("MainWindow", "Do for all in selected document"))
        self.OnTopCheckBox.setText(_translate("MainWindow", "Always on top"))
